# Permalinks
permalink:           pretty

# Setup
title:               Starsep
tagline:             Filip Czaplicki
url:                 https://starsep.com
paginate:            1
baseurl:             "/"

# Custom vars

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

collections:
    dotfiles:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
