baseURL = "https://starsep.com"
defaultContentLanguage = "en"
title = "Filip Czaplicki"
theme = "StarsepTheme"
publishDir = "generated"
[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      #   [[languages.en.menu.main]]
      #     identifier = "about"
      #     pre = ""
      #     post = ""
      #     name = "About me"
      #     url = "/about/"
      #     title = ""
      #     weight = 4
      [[languages.en.menu.main]]
        identifier = "resume"
        pre = ""
        post = ""
        name = "Resume (CV)"
        url = "/cv/cv.pdf"
        title = ""
        weight = 4
  [languages.pl]
    weight = 2
    languageCode = "pl"
    languageName = "Polski"
    [languages.pl.menu]
      [[languages.pl.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posty"
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.pl.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tagi"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.pl.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Kategorie"
        url = "/categories/"
        title = ""
        weight = 3
        #   [[languages.en.menu.main]]
        #     identifier = "about"
        #     pre = ""
        #     post = ""
        #     name = "O mnie"
        #     url = "/about/"
        #     title = ""
        #     weight = 4
      [[languages.pl.menu.main]]
        identifier = "resume"
        pre = ""
        post = ""
        name = "CV"
        url = "../cv/cv.pdf"
        title = ""
        weight = 4

[params]
  gitRepo = "starsep/starsep.github.io"
  defaulttheme = "dark"
[params.search]
  enable = true
  type = "lunr"
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/img/avatar.jpg"
      title = "Filip Czaplicki"
      subtitle = "Android & Web Developer"
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6

  # Social config about the author
  [params.social]
    GitHub = "starsep"
    # Facebook = "Starsep"
    # Gitlab = "starsep"
    # Bitbucket = "starsep"
    # Stackoverflow = "5307071"
    Steam = "starsep"
    Email = "website@starsep.com"
    Googleplay = "Filip+Czaplicki"
    Googlemaps = "108497929507145891013"
    openstreetmap = "starsep"
    MSCCezar = "16053"
    RSS = true

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      # allow raw HTML in Markdown: https://stackoverflow.com/a/63206852 
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
